Repository eclipse-vertx/vertx-sql-client, pull requests merged in 2021-08, with the labels that each got.

#1023 Initial contribution of the Vert.x Oracle Client
  .github/workflows/ci.yml
  pom.xml
  vertx-oracle-client/pom.xml
  vertx-oracle-client/src/main/asciidoc/index.adoc
  vertx-oracle-client/src/main/java/examples/OracleClientExamples.java
  vertx-oracle-client/src/main/java/examples/SqlClientExamples.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/OracleConnectOptions.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/OraclePool.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/OraclePrepareOptions.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/CommandHandler.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/Helper.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleColumnDesc.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleConnectionFactory.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleDatabaseHelper.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleMetadataImpl.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OraclePoolImpl.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleRow.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/RowReader.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/AbstractCommand.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/OracleCursorQueryCommand.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/OraclePreparedBatch.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/OraclePreparedQuery.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/OraclePreparedStatement.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/OracleResponse.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/OracleTransactionCommand.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/PingCommand.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/PrepareStatementCommand.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/QueryCommand.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/SimpleQueryCommand.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/package-info.java
  vertx-oracle-client/src/main/java/io/vertx/oracleclient/spi/OracleDriver.java
  vertx-oracle-client/src/main/resources/META-INF/MANIFEST.MF
  vertx-oracle-client/src/main/resources/META-INF/services/io.vertx.sqlclient.spi.Driver
  vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/OraclePoolTest.java
  vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/OracleTestBase.java
  vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/junit/OracleRule.java
  vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/ClientConfig.java
  vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleCollectorTest.java
  vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleConnectionAutoRetryTest.java
  vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleConnectionTest.java
  vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleDriverTest.java
  vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OraclePreparedBatchTest.java
  vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleSimpleQueryTest.java
  vertx-oracle-client/src/test/resources/tck/import.sql
  vertx-sql-client-templates/src/test/java/io/vertx/sqlclient/templates/TemplateBuilderTest.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/PrepareOptions.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlClient.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlConnection.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/CursorImpl.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PreparedStatementImpl.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/QueryExecutor.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/RowDesc.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SocketConnectionBase.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlClientBase.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlConnectionBase.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlConnectionImpl.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/command/ExtendedQueryCommand.java
  vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/command/PrepareStatementCommand.java
Labels: enhancement

#1017 MSSQL Client Encryption support
  vertx-mssql-client/src/main/asciidoc/index.adoc
  vertx-mssql-client/src/main/java/examples/MSSQLClientExamples.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLConnectOptions.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionFactory.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLSocketConnection.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/EncryptionLevel.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/InitCommandCodec.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/PreLoginCommandCodec.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsLoginSentCompletionHandler.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsSslHandshakeCodec.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/command/PreLoginCommand.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/command/PreLoginResponse.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/client/prelogin/OptionToken.java
  vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/client/prelogin/VersionOptionToken.java
  vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLEncryptionTest.java
  vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLEncryptionTestBase.java
  vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLForcedEncryptionTest.java
  vertx-mssql-client/src/test/java/io/vertx/mssqlclient/junit/MSSQLRule.java
  vertx-mssql-client/src/test/resources/mssql.conf
  vertx-mssql-client/src/test/resources/mssql.key
  vertx-mssql-client/src/test/resources/mssql.pem
  vertx-mssql-client/src/test/resources/ssl.txt
Labels: module:mssql

#1030 Ignore comments in Queries
  vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
  vertx-db2-client/src/test/java/io/vertx/db2client/QueryVariationsTest.java
Labels: bug
